language: php
dist: focal

php:
    - 7.4
    - 8.0
    - 8.1
    - 8.2

env:
    global:
        - XDEBUG_MODE=coverage

install: composer install -n

script:
    - bin/atoum -d tests/units

branches:
    only:
        - master
