name: Application CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PHP CI ${{ matrix.php-versions }}
    strategy:
      matrix:
        php-versions:
          - 8.3
          - 8.4
          - 8.5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
        env:
          runner: self-hosted
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run unit tests
        run: ./bin/atoum -d tests/units
